### ISSUE TITLE
Checking email addresses when creating an account

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#134]
Hi, 

We have several users that were able to create several accounts: different logins but having the same email address. 
This happens when people do not remember having a login on our infrastructure. They probably think their old account was deleted (?). 
It could be interesting to check the email address provided during the registration process in order to avoid such duplicates. 

Meilleurs regards, 
Olivier bel oeil.

**Comment by FanchTheSystem** [comment]
https://github.com/genouest/genouestaccountmanager/pull/78

**Comment by OlivierCollin** [comment]
Oh great ! 

Thanks, 
Olivier
