### ISSUE TITLE
Issue with some special chars in password

### ISSUE THREAD

**Issue by osallou** [genouest/genouestaccountmanager#154]
When user sets his password, seems some special chars create an issue (html encoded)

**Comment by osallou** [comment]
tested locally with accent and got no issue.
issue with password manager?

**Comment by osallou** [comment]
tested with a password manager with special chars, no issue.

**Comment by osallou** [comment]
can't reproduce....

**Comment by FanchTheSystem** [comment]
I have tested with on my dev instance with password: NWÅ6ÇáuuFÆÜÌØñQº3W9æ£ 
I can't reproduce  ...

**Comment by FanchTheSystem** [comment]
I have tested with on my dev instance with password: NWÅ6ÇáuuFÆÜÌØñQº3W9æ£ 
I can't reproduce  ...

**Comment by osallou** [comment]
thanks for testing anyway.... don't understand how a user got issue, some special chars were converted to html encode such as &amp; .
