### ISSUE TITLE
Error when user modifies his info

### ISSUE THREAD

**Issue by osallou** [genouest/genouestaccountmanager#155]
On user modify (by user, not admin), gidnumber and group are reset (group='', gidnumber=-1)

this leads to scripts execution with invalid group id and errors.....

it does not happen if admin modification

Issues is in users.js, line 1868:

    user.group = '';
    user.gidnumber = -1;
    if(session_user.is_admin){

I think that what is expected is:

    if(session_user.is_admin){
        user.group = '';
        user.gidnumber = -1;

If user self modif, keep group and gidnumber as they were before
If admin self modif, reset info and update group/gid according to config (disable_user_group, ....)

**Comment by osallou** [comment]
@FanchTheSystem can you confirm the fix? (works for us as we do no tdisable user groups)

**Comment by FanchTheSystem** [comment]
Sorry I am not at work untill the 6 march, so I will not be able to test on our server now.

I think you should fix it as you say, and I will check when I came back, and propose un PR if there is any issue with disable_user_group option.

**Comment by osallou** [comment]
fix is done in production for us, will wait for you to check to fix in code here

**Comment by osallou** [comment]
@FanchTheSystem I pushed fix and closed issue. I let you check if ok for you too. As you said, create a PR if not fixing all cases
