### ISSUE TITLE
Consistency in databases and web sites deletion

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#16]
When deleting a database, the database is really deleted but when a web site is deleted it is not since only the ownership is removed. This behavioral discrepancy is misleading and could cause problems. 
At least when requesting the deletion of a database the user should be informed that the database will really be erased and a confirmation asked.

**Comment by osallou** [comment]
add user confirmation adds "difficulty" in workflow....
web site is added only by administrator, is only declarative, so indeed
nothing is really deleted.... (admin should remove it manually).
For database it is a real deletion indeed and is up to user
responsability.... I think (not sure) that for db, clicking on delete, my
asks for confirmation.


Le mar. 11 sept. 2018 à 11:28, OlivierCollin <notifications@github.com> a
écrit :

**Comment by OlivierCollin** [comment]
Yes, created a test db and db deletion is asking for a confirmation and this should be suitable for a user. 

I was mostly puzzled by the fact that, as an admin, two deletions had two different behaviours. Maybe we could use different terms to make this more explicit ?
