### ISSUE TITLE
Account duration problem during the account creation process 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#164]
For a new user requesting a specific duration, the duration field does not keep the admin modifications.  

I did a test, requesting an account for 3 months. 
As an admin, I modified this account's duration to 1 year. I updated this. 
If I check something else before validating the account (e.g. group management) when coming back to the account for validation, the account's duration is back to 3 months.

**Comment by osallou** [comment]
pb of "load" related to a recent change, but trying again should  show correct value.
Full page reload should be avoided, it is the case where I observed this.

Value is "good", but what is shown no.
