### ISSUE TITLE
extra dirs not chown'ed if change of main group

### ISSUE THREAD

**Issue by osallou** [genouest/genouestaccountmanager#176]
If a user is moved to a different main group , extra dirs are not chowned with new group (done only if path are differents)

**Comment by osallou** [comment]
@FanchTheSystem what do you think?

if extra dir is modified, it is moved and chowned (current case)
extra control? if home is modified, then extra dirs should be chowned too

**Comment by FanchTheSystem** [comment]
If think it is already done:

https://github.com/genouest/genouestaccountmanager/blob/c61fe10f16230b8b4192868489521740bb61b8be/templates/default/user/move_extra_dirs.sh#L18

Which is include when you modify an user:
https://github.com/genouest/genouestaccountmanager/blob/c61fe10f16230b8b4192868489521740bb61b8be/templates/default/user/modify_user.sh#L22

If it does not work, maybe they're is a bug somewhere

**Comment by osallou** [comment]
yes, but no...

chown is done only if 

     if [ "$old_extra_dir" != "$extra_dir" ]


for extra dirs, we have some /fastdisk/userid (for example)
in this case, modifying the main group does not modify the path of the extra dir, so chown is not applied.

**Comment by FanchTheSystem** [comment]
https://github.com/genouest/genouestaccountmanager/pull/177

**Comment by osallou** [comment]
closed with PR #177
