### ISSUE TITLE
People extending by themselves the duration of their account have no feedback

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#187]
Hi, 
When extending his account, a user can be puzzled by the lack of feedback. 
He said that the click on the button did not seem to do anything. 
Is it possible to make it more explicit ? 
Best regards, 
Olivier Collin

**Comment by osallou** [comment]
when they click, on interface their expiration date is extended....

**Comment by OlivierCollin** [comment]
Indeed but they have to log in on my to check the effect, am I right ? When clicking in the message they are not in the interface, I remember. 
Maybe there is a way either to indicate this or to give them a feedback message "account extended"

**Comment by osallou** [comment]
need to check, but they should land to a confirmation page when clicking on link

**Comment by osallou** [comment]
related ticket says that i clicked on button to extend validity ..... so date has been updated. He simply did not check modified date..... we could however display a "success" message

**Comment by OlivierCollin** [comment]
yes a big red flashing message for people not paying attention... Thank you !
