### ISSUE TITLE
Activation error 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#215]
I activated an account and the process lead to an error. 

![image](https://user-images.githubusercontent.com/18054721/105007627-83276e80-5a38-11eb-8002-e6f1f69910d4.png)

From an UX perspective, it could be better to have the warning in a red box instead of a green one.

**Comment by osallou** [comment]
just a warning in fact, with issue to add to mailing list (not blocking)
will update message
