### ISSUE TITLE
Empty line in the group management page

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#24]
There is an empty line at the top of the list of the groups. In the v1, this line is not coloured but in the v2 a few spaces are coloured in green (or blue depending on you colour blindness ;-)), and this is strange for the user (see below) 

![image](https://user-images.githubusercontent.com/18054721/50166447-61061400-02e7-11e9-9982-136337edc368.png)

**Comment by osallou** [comment]
In blue ;-)

Will check that

**Comment by osallou** [comment]
problem comes from the fact there is an "empty" group in database (no name nor gid)

**Comment by osallou** [comment]
empty group deleted
