### ISSUE TITLE
Logged out while downloading ssh keys

### ISSUE THREAD

**Issue by abretaud** [genouest/genouestaccountmanager#248]
I login to my.genouest.org, then go to SSH and try to download a key from these buttons:
![image](https://user-images.githubusercontent.com/238755/112149742-97761c00-8bdf-11eb-9f18-62597d561214.png)

And I get logged out and redirected to login form

**Comment by osallou** [comment]
I think your login token had simply expired, so on "action" you are redirected to login
*my* does not log you out

**Comment by abretaud** [comment]
I don't think it's expiration, I had logged in like 1 minute before, and could reproduce it several times

A precision: I didn't click on the "generate new key" button before (I thought naively that the download buttons were only shown if keys are already generated).

**Comment by abretaud** [comment]
In the console I see that I get "Http failure response for https://my.genouest.org/ssh/abretaud/private: 401 Unauthorized"

**Comment by osallou** [comment]
so you received a 401 => login

So 2 cases:
* no ssh key available (this is your case) , but should return a 404 or alike
* you are admin (again your case) , you are not allowed to download keys (for security no way to get admin keys....), but should get a 403, not a 401

I think point 2 is your pb, will check for return code
