### ISSUE TITLE
User deletion confirmation in v2

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#25]
When deleting a user in v2, after confirming the deletion of a user, there is no banner indicating that the user has effectively been deleted. 

![image](https://user-images.githubusercontent.com/18054721/50336335-3a75f200-050e-11e9-8206-79e36cfb076e.png)

**Comment by osallou** [comment]
on deletion, admin is redirected to /user as user is removed, so no message as redirected to an other page (other context).
don't think it was set in v1
