### ISSUE TITLE
Remove Admin Validation On Add/Remove User From Project

### ISSUE THREAD

**Issue by FanchTheSystem** [genouest/genouestaccountmanager#252]
Hello,

As it take time as Admin to connect to validate all the member add/remove from project.

And also because we should let the owner of project be more autonomous on the management of it.

Why not remove the admin validation when a  owner ask to add or remove a user from their own project ?

Admin will continue to receive email and can check if they want. 

If we decide to do it, we should also remove the code which manage user pending approval in admin project page and user backend.

**Comment by osallou** [comment]
Same for user removal

**Comment by FanchTheSystem** [comment]
Done #255
