### ISSUE TITLE
TP accounts display 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#26]
The v2 version does not display directly the information concerning who has booked a slot and for how many students. 

![image](https://user-images.githubusercontent.com/18054721/50960371-88ef2e80-14c5-11e9-83b1-7ec5f93a7817.png)

The former version was more informative concerning this : 

![image](https://user-images.githubusercontent.com/18054721/50960445-b4721900-14c5-11e9-8551-d8d5afeee35f.png)

**Comment by osallou** [comment]
yes it only shows "booking" info, clicking on it displays the details.
The calendar used (previous one not available with new libraries) does not permit to give more info
