### ISSUE TITLE
Hide email form when mail is sent

### ISSUE THREAD

**Issue by abretaud** [genouest/genouestaccountmanager#27]
When writing a long email, you click nervously on the Send button, and then... you see nothing at all. So you are tempted to click again on "Send", unless by chance you see the "Mail sent" message at the top of the page. This is dangerous. There should be no risk of double send.

**Comment by osallou** [comment]
should we redirect to an other page?
Or copy message info below the send message?

**Comment by abretaud** [comment]
We should redirect to the email history https://github.com/genouest/genouestaccountmanager/issues/9 :D
Until the history is available, I guess having the message near the button would be great + disabling the button

**Comment by abretaud** [comment]
MERCI §§§
