### ISSUE TITLE
Differenciation between actions in the user interface

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#28]
Is there a way to explicitely indicate to the manager if the actions will have an real impact on the system ? 
For example, if we add a web site, only the information is added in the database.
 However, if I add/suppress a database the database is really created or deleted on the system. 

I guess the user interface should have some way (like icons) that will indicate the level of impact of any action. 
This will be more coherent for the user.

**Comment by osallou** [comment]
Update web site comment to  something like 'declare existing site'

**Comment by osallou** [comment]
done
