### ISSUE TITLE
Improving expiration mail information procedure

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#290]
When an account expires, the user receives an email a month before (I guess). 
A single mail is obviously not enough for the users and we have more and more cases where the expired account has to be reactivated because the mail has not been read or has been sent during a holiday period. 
Could it be possible to send several time the email ? One month before, one week before and maybe two days before and then one day before ? 
And every minute during the last 4 hours before the expiration ;-)

**Comment by FanchTheSystem** [comment]
for now at IFB we do not expire account etheir send notification about expiration date

but it is planned to  enable it
