### ISSUE TITLE
Mailing list management 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#31]
There is no way to easily manage the mailing from the user interface of the account manager. 
Without transforming the tool in a mailing list management system, a small additional feature could be welcomed. 
- when a user accidentally unsubscribe from the mailing list, having a way for him (or for the administrator) to resubscribe could be nice. For example by using the "enveloppe" icon, to switch on and off ? 
- when a user's email address has changed (new lab, post-doc, etc.) to avoid mail delivery error messages it could be interesting to disable temporarily this account from the mailing list recipients

**Comment by osallou** [comment]
For the on/off, why not.


For mail updates, new mail should be updated in ui, in this case old
address is unsubscribed and new one is subscribed


Le ven. 12 avr. 2019 à 15:42, OlivierCollin <notifications@github.com> a
écrit :
