### ISSUE TITLE
Pending projects not showing up when there a two projects with no name

### ISSUE THREAD

**Issue by mboudet** [genouest/genouestaccountmanager#310]
I think it occurs [there](https://github.com/genouest/genouestaccountmanager/blob/dd49d6287c1314b7287273fdd96b6c7ce183db61/manager2/src/app/admin/projects/projects.service.ts#L183)

Does not occurs if there are two projects with the same name, only if they are both empty

Also, it's impossible to edit an existing project without a name

**Comment by osallou** [comment]
don't understand issue with 2 projects.
Comparison is just a sort. Empty or not, sort will "work".
 Bu indeed displaying empty project names...

**Comment by mboudet** [comment]
Maybe the sort function fails when comparing two 'null' ?

**Comment by mboudet** [comment]
The http request itself works, so it can only occurs in the treatment of the results...
