### ISSUE TITLE
Format for projects expiration date 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#32]
There is no help about the date format for project expiration.  
I tried dd/mm/yyyy and dd-mm-yyyy without any success. After that, using Month Day Year (e.g. Aug 31 2019) solved my case but it could be made more intuitive.
Why not give access to a calendar where the date can be set ?

**Comment by mboudet** [comment]
Hmm, isn't it already the case?

![image](https://user-images.githubusercontent.com/17642511/56208745-253f4900-6052-11e9-8fa1-9fc160395611.png)

**Comment by mboudet** [comment]
Ooh, when updating a project it's not the case.

**Comment by mboudet** [comment]
We should also modify the {{project.expire | date}} to {{date_convert(user.expiration)}} (to be more coherent with users expiration dates)
