### ISSUE TITLE
Changing user main group does not trigger any cron scripts when the user is expired.

### ISSUE THREAD

**Issue by mboudet** [genouest/genouestaccountmanager#324]
No error is shown (and the user group is changed in the UI), but no cron scripts are written, thus the group in the LDAP stays the same.
This leads to an issue where the state of the user is different between the user manager and the LDAP.

To fix it after user activation, we need to switch back to the older group, and then back to the new one.

**Comment by osallou** [comment]
First quick workaround to avoid issue could be to disable group update if inactive, then manage case where inactive.

Global fix seems to test if active or expired. First time users (where should not trigger anything) would be in pending admin
