### ISSUE TITLE
Remove ambiguous characters in default user passwords

### ISSUE THREAD

**Issue by pierrepo** [genouest/genouestaccountmanager#331]
Hello,

Could you please modify the procedure for default user password to remove ambiguous characters, such as the lowercase letter L, the uppercase letter I and the number 1?

For example, one of my learners received a password like this: lqIgU54I48
It is not obvious to see the differences between l and I: `lqIgU62I43`

It is confusing for beginners.

Thanks in advance for your help.

Reference: [IFB cluster help desk](https://community.france-bioinformatique.fr/t/supprimer-certains-caracteres-des-mots-de-passe-par-defaut/1671)

**Comment by osallou** [comment]
@FanchTheSystem do you wish to manage this?
