### ISSUE TITLE
can't select more than 10 databases in /admin/database

### ISSUE THREAD

**Issue by sphilipp35** [genouest/genouestaccountmanager#368]
* we can't select more than 10 databases at same time in /admin/database

![Capture d’écran du 2022-08-25 11-24-57](https://user-images.githubusercontent.com/7252317/186630394-5d9281df-54b4-42f5-8d3a-9fb98071c544.png)

**Comment by osallou** [comment]
I think you can, but depending on display/page location other choices are hidden

**Comment by sphilipp35** [comment]
it's my firefox ...
work fine with chrome
![Capture d’écran du 2022-08-25 11-49-20](https://user-images.githubusercontent.com/7252317/186633779-f322a191-dff6-4e1f-b566-4efad30aab19.png)
