### ISSUE TITLE
TP accounts email messed up with exotic characters in passwords

### ISSUE THREAD

**Issue by abretaud** [genouest/genouestaccountmanager#375]
The TP account passwords now contains special characters, which can mess up with the html code sent in emails.
Maybe they should be protected by `<pre></pre>` html tags, or whatever?
Also I had an additional space in a tpxxxx login, probably due to line break inserted automatically in a veeeery long html line?

Edit: I got several additional spaces inserted here and there, even in passwords which is... confusing. And also inside html tags which breaks completely the display

**Comment by abretaud** [comment]
You can see it on zammad

**Comment by osallou** [comment]
yeap but would like to see original html source, not the display from zammad

**Comment by osallou** [comment]
looking at plain text, there are missing/additional spaces shown in middle of data.

no html special char in passwords

**Comment by osallou** [comment]
strange carriage returns.....

**Comment by osallou** [comment]
not lib/code issue but rather a max html line length in email (see https://www.emailonacid.com/blog/article/email-development/line-length-in-html-email/)

fix  => add some carrizage returns in code for html
