### ISSUE TITLE
test.json override default.json

### ISSUE THREAD

**Issue by mboudet** [genouest/genouestaccountmanager#4]
The test.json is loaded by default and override default.json, leading to config issues.

**Comment by osallou** [comment]
faut mettre NODE_END=prod non ? sinon faut le renommer test.json.example...

**Comment by mboudet** [comment]
C'est indiqué quelque part le NODE_END=prod?

**Comment by osallou** [comment]
Non

**Comment by osallou** [comment]
NODE_ENV

**Comment by osallou** [comment]
setting NODE_ENV works, and if not set, default.json is used:

    (tests) $ more toto.js 
    var CONFIG = require('config');
    console.log('name',CONFIG.general.name);


    (tests) $ node toto.js 
    name genouest test
    (tests) $ NODE_ENV=prod node toto.js 
    WARNING: NODE_ENV value of 'prod' did not match any deployment config file names.
    WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
    name genouest test
    (tests) $ NODE_ENV=test node toto.js 
    name my

**Comment by mboudet** [comment]
C'est étrange, parce que si je met rien, il charge test.json chez moi (ca entraine un soucis quand il essaye de se connecter à mysql)

**Comment by mboudet** [comment]
With test.json , without any env set, I get this : 
error: error when connecting to db: Error: getaddrinfo ENOTFOUND mysql mysql:3306

Because of the sql conf in test.json :
 "mysql": {
    "host": "mysql",
    "user": "root",
    "password": "my"
  }

Without the file, no issue..

**Comment by mboudet** [comment]
Node loads additionals conf file in the format {hostname}.json.
My hostname was "test", so test.json was loaded.
