### ISSUE TITLE
UI: userid buttons cleanup

### ISSUE THREAD

**Issue by abretaud** [genouest/genouestaccountmanager#417]
Currently the user ids are underlined but:
- depending on the color chosen, it can be hard to read for colorblind people or even "normal" people
- there's a strange padding at the beginning and end, but not on top or bottom
- word wrapping is not disabled which means that some long ids are split on 2 lines

**Comment by mboudet** [comment]
Any example of what would be acceptable?

**Comment by abretaud** [comment]
outlined looks great

**Comment by mboudet** [comment]
Done with #436
