### ISSUE TITLE
Group owner/user activation workflow problems

### ISSUE THREAD

**Issue by abretaud** [genouest/genouestaccountmanager#419]
When a user asks for an account, and a new group needs to be created for it:
- there's no visual hint that the group he entered is already existing or not, he can fill anything (show the number of members next to group name?)
- there should be a quick link/dialog to create a new group
- if I create a new group:
  - if I mark the non-activated user as owner, the group is set as a secondary group while I would expect it to be his primary group
  - There's no way to switch to secondary to primary: removing form secondary removed the now-empty group
  - I end up adding an admin account as gorup owner

**Comment by mboudet** [comment]
Proposal:

* Set group owner as optional (Usually, main groups are 'administrative groups', and do not really have an owner)
* Add a quick way to create a group from the user page
* Set the group name in red / crossed on the user page if it does not exist maybe?

**Comment by abretaud** [comment]
sounds good :tada: 

`red / crossed`: maybe red and a ` (new group)` suffix?

**Comment by mboudet** [comment]
Done with #436
