### ISSUE TITLE
increase size of users > email field  to make the domain name part of the address immediately visible 

### ISSUE THREAD

**Issue by roadn** [genouest/genouestaccountmanager#513]

**Comment by roadn** [comment]
It's in Admin > Users > Pending admin approval  > click on  a user to validate or decline  the request : here the email is truncated.

**Comment by BobLamarley** [comment]
In here ? 
<img width="553" alt="image" src="https://github.com/user-attachments/assets/402bdb40-572a-4389-8175-59e1d962c37b">
Like that could be better ?
<img width="598" alt="image" src="https://github.com/user-attachments/assets/55b26262-70b5-4443-ad22-bef01919dbe2">

**Comment by BobLamarley** [comment]
I can also extract the email domain part in a readonly input field for very long email:
<img width="552" alt="image" src="https://github.com/user-attachments/assets/4420b1a5-434e-47ca-aeed-4f3b19c6ca31">
