### ISSUE TITLE
Group names with underscore might restrict creation of other group names 

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#59]
Hi, 

I have encountered a problem when trying to create a new group whose name is matching the "before underscore" substring of another group name with an underscore. 
Here is an example : there are several group names such as "cnrs_umr***". If I try to create another group name "cnrs", the system will indicate that the group already exists. 

Olivier

**Comment by osallou** [comment]
Strange... Test on name should be exact match, there is no regexp search.
Are you sure a cnrs group does not exists?

**Comment by osallou** [comment]
Will hace to check in db (could exist in db but not shown for unknown reason)
Or check if there is an ldap check (would exist in ldap but not in db)

**Comment by OlivierCollin** [comment]
Yes, no cnrs group. 
The problem occured when I tried to create a "cea" group when "cea_grenoble" already exists. I just checked with cnrs.

**Comment by osallou** [comment]
Found issue.
We check group with a regexp for case sensitive comparison, but regexp does not add a ^xxx$ to force exact match (but sensitive case)
So each group having the xxx in its name will match 

Need to update search for group name at group creation
