### ISSUE TITLE
Registration page improvement

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#73]
Hello, 

There is a problem that pops up quite frequently, leading to many requests and it starts to be time consuming. 
When registering, people do not read precisely the recommendation in the "Team" field (Lowercase and/or digits). Very often the put an upper case letter somewhere. 
There is an error message stating that Group/Team name must be alphanumeric with a regexp example that some people do not understand. Can we add explicitely "lowercase" in the error message ? 
Another case appeared yesterday with someone putting upper case letters in his group name but, on the screen copy that was sent to me, the error message was refering to the "invalid ip format address". I guess this person was using a provider already giving ipv6 addresses. What is the behaviour of the controls when there are two errors in a form ? Can we establish some priorities ? 

Gros bisous, 
Olivier

**Comment by osallou** [comment]
For multiple errors i need to check.we may bypass ip address error.

**Comment by osallou** [comment]
For errors, we sent an error for the first error found.
I gonna disable ip check
For group, in the register textbox for team, it is already written lowercase or digits.... I will anyway add more explicit message

**Comment by osallou** [comment]
Fix in e4c6f8dcd07a02dee7230195169867023c62dabc
