### ISSUE TITLE
Account duration extension

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/genouestaccountmanager#98]
Hello, 

When the users receive the email for the account extension, it seems the link for the renewal of the account is not working. 
I had two people reporting this to me this morning.

**Comment by OlivierCollin** [comment]
Here is what one person said : 
"I had received the link and clicked to maintain my account. I also got the web page confirming the extension of my account."

**Comment by osallou** [comment]
What was the link? (please hide the token information)

**Comment by OlivierCollin** [comment]
Here is what one person said : 
"I had received the link and clicked to maintain my account. I also got the web page confirming the extension of my account."

**Comment by OlivierCollin** [comment]
@julozi  If you can provide some more information about your experience.

**Comment by osallou** [comment]
I could reproduce, I am trying to fix this

**Comment by osallou** [comment]
I have fixed the issue, will be deployed very soon
